spring:
  application:
    name: werewolf-assistant

  ai:
    dashscope:
      api-key: sk-79729ca14be743e7a33ba6591c788b07
      chat:
        api-key: sk-79729ca14be743e7a33ba6591c788b07

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/werewolf_assistant?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
      jakarta:
        persistence:
          jdbc:
            driver: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/werewolf_assistant?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
            user: root
            password: root

server:
  port: 8012
